export default () => ({
  services: [
    {
      id: '1',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '2',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '3',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '4',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '5',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '6',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '7',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '8',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
  ],
  products: [
    {
      id: '1',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '2',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: '',
      cost: '100',
    },
    {
      id: '3',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '4',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '5',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '6',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '7',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '8',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    }
  ],
  vacancies: [
    {
      id: '1',
      title: 'Вакансия 1',
      desc: 'Описание вакансии 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '20000',
    },
  ],
})
