export default () => ({
  services: [
    {
      id: '31',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: '',
      cost: '100',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '60',
      title: 'Услуга 2',
      desc: 'Описание услуги 2',
      category: 'Категория',
      imgUrl: 'http://www.eastplum.com/wp-content/uploads/2021/01/image.jpg',
      cost: '200',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '330',
      title: 'Услуга 3',
      desc: 'Описание услуги 3',
      category: 'Категория',
      imgUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.JEJraLejCsHhXPHAzB2eJQHaEK%26pid%3DApi&f=1',
      cost: '300',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '42',
      title: 'Услуга 4',
      desc: 'Описание услуги 4',
      category: 'Категория',
      imgUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.I4s5pOeM2WFdYpcnFiJpiwHaE8%26pid%3DApi&f=1',
      cost: '400',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '30',
      title: 'Услуга 5',
      desc: 'Описание услуги 5',
      category: 'Категория',
      imgUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.XF97w0y_ZHdmwTRv1dtqMAHaEO%26pid%3DApi&f=1',
      cost: '500',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '1',
      title: 'Услуга 6',
      desc: 'Описание услуги 6',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '600',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '10',
      title: 'Услуга 7',
      desc: 'Описание услуги 7',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '700',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
    {
      id: '84',
      title: 'Услуга 8',
      desc: 'Описание услуги 8',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '800',
      inCart: 0,
      inStorage: 1,
      itemCommonPrice: 0,
      type: 'service',
    },
  ],
  products: [
    {
      id: '92',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '78',
      title: 'Товар 2',
      desc: 'Описание товара 2',
      category: 'Категория',
      imgUrl: '',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '33',
      title: 'Товар 3',
      desc: 'Описание товара 3',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '15',
      title: 'Товар 4',
      desc: 'Описание товара 4',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '700',
      title: 'Товар 5',
      desc: 'Описание товара 5',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '436',
      title: 'Товар 6',
      desc: 'Описание товара 6',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '247',
      title: 'Товар 7',
      desc: 'Описание товара 7',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    },
    {
      id: '358',
      title: 'Товар 8',
      desc: 'Описание товара 8',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
      inCart: 0,
      inStorage: 10,
      itemCommonPrice: 0,
      type: 'product',
    }
  ],
  vacancies: [
    {
      id: '1',
      title: 'Вакансия 1',
      desc: 'Описание вакансии 1',
      category: 'Категория',
      imgUrl: '/images/vacancy.jpg',
      cost: '20000',
    },
  ],
  mainPage: [
    {
      title: 'Каталог',
      url: 'catalog',
      imgUrl: '/images/catalog.jpg',
      desc: 'Наша компания предлагает огромный ассортимент товаров, связанных с погребением.\n' +
        'Подробнее, вы можете ознакомиться с ассортиментов в разделе "Каталог".'
    },
    {
      title: 'Контакты',
      url: 'contacts',
      imgUrl: '/images/contacts.jpg',
      desc: 'О том, как связаться с нами вы можете в разделе "Контакты".'
    },
  ],
})
