export default () => ({
  services: [
    {
      id: '1',
      title: 'Услуга 1',
      desc: 'Описание услуги 1',
      category: 'Категория',
      imgUrl: '',
      cost: '100',
    },
    {
      id: '2',
      title: 'Услуга 2',
      desc: 'Описание услуги 2',
      category: 'Категория',
      imgUrl: 'http://www.eastplum.com/wp-content/uploads/2021/01/image.jpg',
      cost: '200',
    },
    {
      id: '3',
      title: 'Услуга 3',
      desc: 'Описание услуги 3',
      category: 'Категория',
      imgUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.JEJraLejCsHhXPHAzB2eJQHaEK%26pid%3DApi&f=1',
      cost: '300',
    },
    {
      id: '4',
      title: 'Услуга 4',
      desc: 'Описание услуги 4',
      category: 'Категория',
      imgUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.I4s5pOeM2WFdYpcnFiJpiwHaE8%26pid%3DApi&f=1',
      cost: '400',
    },
    {
      id: '5',
      title: 'Услуга 5',
      desc: 'Описание услуги 5',
      category: 'Категория',
      imgUrl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.XF97w0y_ZHdmwTRv1dtqMAHaEO%26pid%3DApi&f=1',
      cost: '500',
    },
    {
      id: '6',
      title: 'Услуга 6',
      desc: 'Описание услуги 6',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '600',
    },
    {
      id: '7',
      title: 'Услуга 7',
      desc: 'Описание услуги 7',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '700',
    },
    {
      id: '8',
      title: 'Услуга 8',
      desc: 'Описание услуги 8',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '800',
    },
  ],
  products: [
    {
      id: '1',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '100',
    },
    {
      id: '2',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: '',
      cost: '100',
    },
    {
      id: '3',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '4',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '5',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '6',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '7',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    },
    {
      id: '8',
      title: 'Товар 1',
      desc: 'Описание товара 1',
      category: 'Категория',
      imgUrl: 'http://www.sunhome.ru/i/wallpapers/62/skachat-detskie-kartinki.orig.jpg',
      cost: '100',
    }
  ],
  vacancies: [
    {
      id: '1',
      title: 'Вакансия 1',
      desc: 'Описание вакансии 1',
      category: 'Категория',
      imgUrl: 'https://bipbap.ru/wp-content/uploads/2017/04/1423036688.jpg',
      cost: '20000',
    },
  ],
})
